### ISSUE TITLE
Document minimum required permissions for the PAT

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/gitcellar#11]
Users might wish to use a PAT with the minimum required permissions to list the repos & download the migration archives. What are the minimum required permissions?

I got it to work with a PAT with `admin:org`, `repo`. Can we use even less?

**Comment by maelle** [comment]
The PAT I use has no scope, just "public access". However, it means it can't list private repositories so I have to register those in a JSON that our backup script uses. I wanted to have a PAT with a minimal scope, so that was the compromise.

Wanna make a PR for the docs? :smile_cat:
