### ISSUE TITLE
Argument question: keep.

### ISSUE THREAD

**Issue by DanWismer** [ropensci-org/gitcellar#16]
Hi,

I am not 100% sure if I understand the `keep` argument.

For example. If I go:
```
download_organization_repos(
  organizations = "NCC-CNC",
  extra_repos = NULL,
  keep = c("rollup", "impact"),
  dest_folder = getwd()
)
````

Will this archive and download only those two public repos?

**Comment by maelle** [comment]
Yes! Do you have any suggestion of how we could clarify the docs in https://docs.ropensci.org/gitcellar/reference/download_organization_repos.html? Thank you :-)

**Comment by DanWismer** [comment]
Awesome, thanks! 

Maybe having something like: "a character vector of repository names to explicitly archive and download. If this vector is length zero, all organization repositories are archived and downloaded."  

I was just getting tripped up with the word "keep". Sorry, I am not an expert on GitHub and I am learning as I go here.

**Comment by maelle** [comment]
I've updated the docs, thanks a ton!

**Comment by DanWismer** [comment]
Thanks maelle!
