### ISSUE TITLE
Update necessary permissions in documentation

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/gitcellar#20]
My backup workflow suddenly stopped working and only restarted when I updated the PAT to include the `admin:org` scope (note that `read:org` was not enough), as per the [endpoint documentation](https://docs.github.com/en/migrations/using-ghe-migrator/exporting-migration-data-from-githubcom):

> [Generate an access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with the repo and admin:org scopes on GitHub.com.

**Comment by maelle** [comment]
oh right I had to do that and forgot to update the docs :woman_facepalming: thank you!!

**Comment by maelle** [comment]
I pushed a fix, feedback welcome. Thank you!
