### ISSUE TITLE
Finding source code within the downloaded archive?

### ISSUE THREAD

**Issue by k-doering-NOAA** [ropensci-org/gitcellar#8]
I'm having trouble finding the actual source code after uncompressing the *tar.gz file locally. I'm not sure if it is missing or if I just cannot find it?

**Comment by k-doering-NOAA** [comment]
For clarity, I see plenty of other files, pertaining to issues and other aspects of Github, but I just can't find the code itself somehow!

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA FYI

**Comment by maelle** [comment]
Oh another **crucial** thing missing from the docs!

To see the code you need to clone the git repository that's in the folder `repositories/`. In that folder there is one bare repository per GitHub repository. Its being bare means there's only the `.git/` folder but once you clone it elsewhere you get a non bare repository and you can see the files. Here is a small reprex below.

```r
# Download a few repos
gitcellar::download_organization_repos(c("maelle-test"))
#> Launching archive creation for organization maelle-test
#> Launching backup of maelle-test/testy at 2022-07-28 08:30:23
#> Launching backup of maelle-test/testy2 at 2022-07-28 08:30:27
#> Waiting one minute for things to kick off properly before downloads...
#> 2 archives to be saved.
#> Spent 2.07265218098958e-05 minutes
#> Saving archive of maelle-test/testy at 2022-07-28 08:31:31
#> Saving archive of maelle-test/testy2 at 2022-07-28 08:31:35
#> # A tibble: 2 × 2
#>   repos  exported
#>   <chr>  <lgl>   
#> 1 testy  TRUE    
#> 2 testy2 TRUE
archives_dir <- getwd()

# Create a temporary directory
temp_dir <- withr::local_tempdir()

# Untar the tar.gz
tar_file <- sprintf("%s/archive-maelle-test_testy/maelle-test_testy_migration_archive.tar.gz", archives_dir)
tar_file
#> [1] "/tmp/RtmpRF3uZc/reprex-1ed75e8fbd-vague-bull/archive-maelle-test_testy/maelle-test_testy_migration_archive.tar.gz"
untar(tar_file, exdir = archives_dir)
# Clone one repo
archive_url <- sprintf("file://%s/%s/", archives_dir, "repositories/maelle-test/testy.git")
archive_url
#> [1] "file:///tmp/RtmpRF3uZc/reprex-1ed75e8fbd-vague-bull/repositories/maelle-test/testy.git/"
gert::git_clone(archive_url, bare = FALSE)
fs::dir_ls(file.path(getwd(), "testy.git"), recurse = TRUE)
#> /tmp/RtmpRF3uZc/reprex-1ed75e8fbd-vague-bull/testy.git/DESCRIPTION
#> /tmp/RtmpRF3uZc/reprex-1ed75e8fbd-vague-bull/testy.git/NAMESPACE
#> /tmp/RtmpRF3uZc/reprex-1ed75e8fbd-vague-bull/testy.git/testy.Rproj
```

Is this clearer? Do you think there should be a function that helps using the archive in gitcellar? Would you like to make a PR to clarify the docs?

**Comment by k-doering-NOAA** [comment]
Thanks so much @maelle! The reprex is really helpful. I'll give it a try and can submit a PR to add to the docs based on your comments, thank you!

**Comment by k-doering-NOAA** [comment]
@maelle, do you have thoughts on where the cloned github repo should go? My hope is to store the source code (at least the file in the main branch at the time the repo is cloned) along with all of the other files that `gitcellar::download_organization_repos` creates (so untar, add the sourcecode, re-tar. I'm not sure if I should make a new subfolder within the `*.git` subfolder, if one of the existing subfolders should be used, or something else? 

Adding: an initial thought is creating a subfolder called "source_code" within the `*.git` subfolder

**Comment by maelle** [comment]
So, at the moment at rOpenSci we have all the archives on Digital Ocean and we do not "unbare" the bare git repos. I imagine we would only use them if something goes wrong or when we need to do an analysis over all repos. So I do not have thought on a good location other that it should probably be _near_ the `*.git` subfolder to not mess up the git repo. :thinking: Not sure it helps :sweat_smile:

**Comment by k-doering-NOAA** [comment]
Thanks! I figured the ropensci needs are a little different, and I wasn't aware of the concept of a "bare" git repo. Thanks for the tip not to mess with the structure of the bare git repo.

Am I right in that the goal with `gitcellar::download_organization_repos` is to backup everything on github except for the source code itself?

**Comment by k-doering-NOAA** [comment]
Thanks for all the help! The solution I came up with was just to clone the repository separately and save a zip file with the source code. An example of doing this with {gitcellar}:

```r
folder_to_clone_in <- "my_folder"
archive_url <- "https://github.com/ropensci-org/gitcellar.git"
current_zip_name <- "source_code.zip"
gert::git_clone(archive_url, bare = FALSE, path = folder_to_clone_in)
gert::git_archive_zip(file = current_zip_name, repo = folder_to_clone_in)
```

**Comment by maelle** [comment]
The bare repository actually is already a backup since when you clone it, you can see all the files.
So you don't need to re-clone from GitHub, you can clone from the bare repository to another folder on the same machine.

I'm reopening to update docs.

Thanks a lot for using & reporting code/docs problems!

**Comment by maelle** [comment]
Another tip, with the dev version of gert you can list files in a bare repo:

```r
install.packages("gert", repos = "https://ropensci.r-universe.dev")
```
And then:
``` r
repo_path <- "archive-maelle-test_testy/repositories/maelle-test/testy.git"
gert::git_ls(repo = repo_path, ref = "main")
#> # A tibble: 5 × 4
#>   path          filesize modified            created            
#> * <chr>            <dbl> <dttm>              <dttm>             
#> 1 .Rbuildignore        0 1970-01-01 01:00:00 1970-01-01 01:00:00
#> 2 .gitignore           0 1970-01-01 01:00:00 1970-01-01 01:00:00
#> 3 DESCRIPTION          0 1970-01-01 01:00:00 1970-01-01 01:00:00
#> 4 NAMESPACE            0 1970-01-01 01:00:00 1970-01-01 01:00:00
#> 5 testy.Rproj          0 1970-01-01 01:00:00 1970-01-01 01:00:00
```

<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by k-doering-NOAA** [comment]
This is great to know, thank you for explaining the bare git repo! I get it now 😃
